### ISSUE TITLE
Questions about  Carplay of Apple.

### ISSUE THREAD

**Issue by zhangy-yu** [cphatt/ZKCD#1]
Please ask some questions. If you can reply me, I will be very grateful.

Has the project completed the function of Carplay?

What platform is it based on? Linux and others. I currently want to make a demo based on the Android platform and complete the Carplay function.

Can you give me some advice?

**Comment by cphatt** [comment]
well，This is a navigator project based on LINUX，Contains Carplay。Most of the source code is provided by the original factory，We just provide the scheme。

**Comment by zhangy-yu** [comment]
I see, THANK YOU.
